[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Arnavion <me@arnavion.dev>"]
edition = "2021"

[dependencies]
backtrace = "0.3"
num-complex = "0.4"
num-traits = "0.2"
once_cell = "1.5"
petgraph = "0.6"
regex = "1.4"
